# LANGUAGE message translation file for plpython
# Copyright (C) 2009 PostgreSQL Global Development Group
# This file is distributed under the same license as the PostgreSQL package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2009.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PostgreSQL 8.4\n"
"Report-Msgid-Bugs-To: pgsql-bugs@postgresql.org\n"
"POT-Creation-Date: 2009-04-15 21:08+0000\n"
"PO-Revision-Date: 2009-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2;\n"

#: plpython.c:420 plpython.c:445
msgid "unexpected return value from trigger procedure"
msgstr ""

#: plpython.c:421
msgid "Expected None or a string."
msgstr ""

#: plpython.c:435
msgid ""
"PL/Python trigger function returned \"MODIFY\" in a DELETE trigger -- ignored"
msgstr ""

#: plpython.c:446
msgid "Expected None, \"OK\", \"SKIP\", or \"MODIFY\"."
msgstr ""

#: plpython.c:493
msgid "TD[\"new\"] deleted, cannot modify row"
msgstr ""

#: plpython.c:496
msgid "TD[\"new\"] is not a dictionary"
msgstr ""

#: plpython.c:515
#, c-format
msgid "name of TD[\"new\"] attribute at ordinal position %d is not a string"
msgstr ""

#: plpython.c:519
#, c-format
msgid ""
"key \"%s\" found in TD[\"new\"] does not exist as a column in the triggering "
"row"
msgstr ""

#: plpython.c:540
#, c-format
msgid ""
"could not compute string representation of Python object in PL/Python "
"function \"%s\" while modifying trigger row"
msgstr ""

#: plpython.c:622
msgid "could not create new dictionary while building trigger arguments"
msgstr ""

#: plpython.c:830
msgid "unsupported set function return mode"
msgstr ""

#: plpython.c:831
msgid ""
"PL/Python set-returning functions only support returning only value per call."
msgstr ""

#: plpython.c:843
msgid "returned object cannot be iterated"
msgstr ""

#: plpython.c:844
msgid "PL/Python set-returning functions must return an iterable object."
msgstr ""

#: plpython.c:872
msgid "error fetching next item from iterator"
msgstr ""

#: plpython.c:890
msgid "PL/Python function with return type \"void\" did not return None"
msgstr ""

#: plpython.c:937
#, c-format
msgid ""
"could not create string representation of Python object in PL/Python "
"function \"%s\" while creating return value"
msgstr ""

#: plpython.c:986
#, c-format
msgid "PL/Python function \"%s\" failed"
msgstr ""

#: plpython.c:1056
#, c-format
msgid ""
"PyList_SetItem() failed for PL/Python function \"%s\" while setting up "
"arguments"
msgstr ""

#: plpython.c:1060
#, c-format
msgid ""
"PyDict_SetItemString() failed for PL/Python function \"%s\" while setting up "
"arguments"
msgstr ""

#: plpython.c:1238
msgid "trigger functions can only be called as triggers"
msgstr ""

#: plpython.c:1242
#, c-format
msgid "PL/Python functions cannot return type %s"
msgstr ""

#: plpython.c:1321
#, c-format
msgid "PL/Python functions cannot accept type %s"
msgstr ""

#: plpython.c:1415
#, c-format
msgid "could not compile PL/Python function \"%s\""
msgstr ""

#: plpython.c:1727
msgid "could not create new dictionary"
msgstr ""

#: plpython.c:1814 plpython.c:1903 plpython.c:1974
msgid "could not compute string representation of Python object"
msgstr ""

#: plpython.c:1828
#, c-format
msgid "key \"%s\" not found in mapping"
msgstr ""

#: plpython.c:1829
msgid ""
"To return null in a column, add the value None to the mapping with the key "
"named after the column."
msgstr ""

#: plpython.c:1873
msgid "length of returned sequence did not match number of columns in row"
msgstr ""

#: plpython.c:1987
#, c-format
msgid "attribute \"%s\" does not exist in Python object"
msgstr ""

#: plpython.c:1988
msgid ""
"To return null in a column, let the returned object have an attribute named "
"after column with value None."
msgstr ""

#: plpython.c:2210
msgid "plan.status takes no arguments"
msgstr ""

#: plpython.c:2340 plpython.c:2479
msgid "transaction aborted"
msgstr ""

#: plpython.c:2347
msgid "invalid arguments for plpy.prepare"
msgstr ""

#: plpython.c:2354
msgid "second argument of plpy.prepare must be a sequence"
msgstr ""

#: plpython.c:2399
#, c-format
msgid "plpy.prepare: type name at ordinal position %d is not a string"
msgstr ""

#: plpython.c:2426
msgid "plpy.prepare does not support composite types"
msgstr ""

#: plpython.c:2454
msgid "unrecognized error in PLy_spi_prepare"
msgstr ""

#: plpython.c:2456 plpython.c:2618 plpython.c:2665
#, c-format
msgid "in PL/Python function \"%s\""
msgstr ""

#: plpython.c:2492
msgid "plpy.execute expected a query or a plan"
msgstr ""

#: plpython.c:2509
msgid "plpy.execute takes a sequence as its second argument"
msgstr ""

#: plpython.c:2525 plpython.c:2552
#, c-format
msgid "PL/Python function \"%s\" could not execute plan"
msgstr ""

#: plpython.c:2529
#, c-format
msgid "Expected sequence of %d argument, got %d: %s"
msgid_plural "Expected sequence of %d arguments, got %d: %s"
msgstr[0] ""
msgstr[1] ""

#: plpython.c:2616
msgid "unrecognized error in PLy_spi_execute_plan"
msgstr ""

#: plpython.c:2637
#, c-format
msgid "SPI_execute_plan failed: %s"
msgstr ""

#: plpython.c:2663
msgid "unrecognized error in PLy_spi_execute_query"
msgstr ""

#: plpython.c:2674
#, c-format
msgid "SPI_execute failed: %s"
msgstr ""

#: plpython.c:2734
msgid "unrecognized error in PLy_spi_execute_fetch_result"
msgstr ""

#: plpython.c:2770
msgid "untrapped error in initialization"
msgstr ""

#: plpython.c:2773
msgid "could not create procedure cache"
msgstr ""

#: plpython.c:2785
msgid "could not import \"__main__\" module"
msgstr ""

#: plpython.c:2792
msgid "could not initialize globals"
msgstr ""

#: plpython.c:2894
msgid "could not parse error message in plpy.elog"
msgstr ""

#: plpython.c:2990
#, c-format
msgid "PL/Python: %s"
msgstr ""

#: plpython.c:2991
#, c-format
msgid "%s"
msgstr "%s"

#: plpython.c:3081
msgid "out of memory"
msgstr "не хватает памяти"
